import type { FindCategory, UserRole } from "@prisma/client";

export type FindTestProfile = {
  email: string;
  nickname: string;
  safeId: string;
  role: UserRole;
  category: FindCategory;
  city: string;
  metro?: string;
  isOnline: boolean;
  isAvailableNow: boolean;
  budgetFrom: number;
  bio: string;
  services: string[];
  credits: string[];
  portfolioLinks: string[];
  contactTelegram?: string;
  contactUrl?: string;
};

export const findTestProfiles: FindTestProfile[] = [
  {
    email: "producer@artsafehub.app",
    nickname: "Misha Prod",
    safeId: "SAFE-SP-001",
    role: "SPECIALIST",
    category: "PRODUCER",
    city: "Москва",
    metro: "Курская",
    isOnline: true,
    isAvailableNow: true,
    budgetFrom: 15000,
    bio: "Продюсер и аранжировщик. Делаю трек от идеи до финального референса.",
    services: ["Продакшн", "Аранжировка", "Саунд-дизайн"],
    credits: ["Marta Ray", "NEONVIBE", "KAIA"],
    portfolioLinks: ["https://example.com/misha-prod", "https://soundcloud.com/misha-prod"],
    contactTelegram: "https://t.me/misha_prod"
  },
  {
    email: "engineer@artsafehub.app",
    nickname: "Lena Mix",
    safeId: "SAFE-SP-002",
    role: "SPECIALIST",
    category: "AUDIO_ENGINEER",
    city: "Санкт-Петербург",
    metro: "Петроградская",
    isOnline: true,
    isAvailableNow: false,
    budgetFrom: 12000,
    bio: "Инженер сведения и мастеринга. Работаю с поп, инди и электроникой.",
    services: ["Сведение", "Мастеринг"],
    credits: ["AURA", "Maks Vento", "NIKA NOVA"],
    portfolioLinks: ["https://example.com/lena-mix", "https://mixing.example/lena"],
    contactTelegram: "https://t.me/lena_mix"
  },
  {
    email: "producer2@artsafehub.app",
    nickname: "Artem Pulse",
    safeId: "SAFE-SP-003",
    role: "SPECIALIST",
    category: "PRODUCER",
    city: "Москва",
    metro: "Савёловская",
    isOnline: true,
    isAvailableNow: true,
    budgetFrom: 18000,
    bio: "Продюсер в жанрах alt-pop и dance. Упор на хук, ритмику и драматургию трека.",
    services: ["Продакшн", "Song doctor", "Подготовка демо"],
    credits: ["Mona K", "Dari West", "RUDI"],
    portfolioLinks: ["https://example.com/artem-pulse"],
    contactTelegram: "https://t.me/artem_pulse"
  },
  {
    email: "engineer2@artsafehub.app",
    nickname: "Roman Glue",
    safeId: "SAFE-SP-004",
    role: "SPECIALIST",
    category: "AUDIO_ENGINEER",
    city: "Казань",
    metro: "Козья слобода",
    isOnline: true,
    isAvailableNow: true,
    budgetFrom: 10000,
    bio: "Микс-инженер. Уплотняю звук и собираю микс под стриминг.",
    services: ["Сведение", "Тюнинг вокала", "Стерео мастеринг"],
    credits: ["KRUZ", "MIA LANE"],
    portfolioLinks: ["https://example.com/roman-glue"],
    contactTelegram: "https://t.me/roman_glue"
  },
  {
    email: "promo1@artsafehub.app",
    nickname: "Release Orbit",
    safeId: "SAFE-PR-001",
    role: "SPECIALIST",
    category: "PROMO_CREW",
    city: "Москва",
    metro: "Таганская",
    isOnline: true,
    isAvailableNow: true,
    budgetFrom: 25000,
    bio: "Промо-команда для релизов: стратегия, PR, Telegram/shorts-посевы и запуск кампании.",
    services: ["PR релиза", "Посевы", "Контент-план", "SMM сопровождение"],
    credits: ["NIKA NOVA", "RUDI", "Mona K"],
    portfolioLinks: ["https://example.com/release-orbit"],
    contactTelegram: "https://t.me/release_orbit_team"
  },
  {
    email: "promo2@artsafehub.app",
    nickname: "Neon Promo Lab",
    safeId: "SAFE-PR-002",
    role: "SPECIALIST",
    category: "PROMO_CREW",
    city: "Санкт-Петербург",
    metro: "Горьковская",
    isOnline: true,
    isAvailableNow: false,
    budgetFrom: 18000,
    bio: "Команда промо для инди/поп артистов: упаковка релиза, digital PR и запуск рекламных связок.",
    services: ["Digital PR", "SMM", "Рекламные креативы", "Релизный план"],
    credits: ["AURA", "Vera Sun", "North Kids"],
    portfolioLinks: ["https://example.com/neon-promo-lab"],
    contactTelegram: "https://t.me/neonpromolab"
  },
  {
    email: "studio@artsafehub.app",
    nickname: "Frame Studio",
    safeId: "SAFE-ST-001",
    role: "STUDIO",
    category: "RECORDING_STUDIO",
    city: "Алматы",
    metro: "Байконур",
    isOnline: false,
    isAvailableNow: true,
    budgetFrom: 8000,
    bio: "Студия записи для вокала и инструментов. Есть отдельная vocal booth.",
    services: ["Запись вокала", "Студийная смена", "Подкаст-сессия"],
    credits: ["KZ Flow", "Alem Beats", "Runa"],
    portfolioLinks: ["https://framestudio.example"],
    contactUrl: "https://framestudio.example"
  },
  {
    email: "studio2@artsafehub.app",
    nickname: "Neon Room",
    safeId: "SAFE-ST-002",
    role: "STUDIO",
    category: "RECORDING_STUDIO",
    city: "Москва",
    metro: "Белорусская",
    isOnline: false,
    isAvailableNow: false,
    budgetFrom: 2200,
    bio: "Студия с фокусом на rap/pop запись и вокальный продакшн.",
    services: ["Запись вокала", "Аренда студии", "Репетиция live-сета"],
    credits: ["LIL BERG", "SONIA RED", "PAVEL RO"],
    portfolioLinks: ["https://example.com/neon-room"],
    contactTelegram: "https://t.me/neon_room_studio",
    contactUrl: "https://example.com/neon-room"
  },
  {
    email: "studio3@artsafehub.app",
    nickname: "Tape House",
    safeId: "SAFE-ST-003",
    role: "STUDIO",
    category: "RECORDING_STUDIO",
    city: "Санкт-Петербург",
    metro: "Площадь Восстания",
    isOnline: false,
    isAvailableNow: true,
    budgetFrom: 2000,
    bio: "Уютная студия для сольных артистов и small-band сессий.",
    services: ["Запись вокала", "Запись гитары", "Сведение под ключ"],
    credits: ["Vera Sun", "Polina Sky", "North Kids"],
    portfolioLinks: ["https://example.com/tape-house"],
    contactTelegram: "https://t.me/tape_house"
  },
  {
    email: "coverartist1@artsafehub.app",
    nickname: "Nora Cover Art",
    safeId: "SAFE-CV-001",
    role: "SPECIALIST",
    category: "COVER_ARTIST",
    city: "Москва",
    metro: "Чистые пруды",
    isOnline: true,
    isAvailableNow: true,
    budgetFrom: 12000,
    bio: "Художник обложек для single и EP. Делаю иллюстрации под настроение трека и референсы.",
    services: ["Иллюстрация для обложки", "Обложка single", "Арт-пак для релиза"],
    credits: ["MIA LANE", "Dari West", "Vera Sun"],
    portfolioLinks: ["https://example.com/nora-cover-art"],
    contactTelegram: "https://t.me/nora_cover_art"
  },
  {
    email: "coverphoto1@artsafehub.app",
    nickname: "CoverShot Lab",
    safeId: "SAFE-CV-002",
    role: "SPECIALIST",
    category: "COVER_PHOTOGRAPHER",
    city: "Санкт-Петербург",
    metro: "Невский проспект",
    isOnline: false,
    isAvailableNow: false,
    budgetFrom: 15000,
    bio: "Фотограф для обложек релизов: студийные и уличные съёмки, ретушь и подготовка под стриминги.",
    services: ["Фотосъёмка для обложки", "Ретушь", "Подготовка файлов под DSP"],
    credits: ["AURA", "NEONVIBE", "North Kids"],
    portfolioLinks: ["https://example.com/covershot-lab"],
    contactTelegram: "https://t.me/covershot_lab"
  },
  {
    email: "videographer1@artsafehub.app",
    nickname: "Snap Frame Video",
    safeId: "SAFE-VD-001",
    role: "SPECIALIST",
    category: "VIDEOGRAPHER",
    city: "Киев",
    metro: "Олимпийская",
    isOnline: true,
    isAvailableNow: true,
    budgetFrom: 12000,
    bio: "Видеограф для short-form контента: сниппеты, reels, вертикальные тизеры и backstage.",
    services: ["Сниппеты/Reels", "Промо-тизеры", "Short-form монтаж"],
    credits: ["RUDI", "Mona K", "PAVEL RO"],
    portfolioLinks: ["https://example.com/clip-frame-team"],
    contactTelegram: "https://t.me/clip_frame_team"
  },
  {
    email: "clipteam1@artsafehub.app",
    nickname: "Moonlight Clip Prod",
    safeId: "SAFE-CP-001",
    role: "SPECIALIST",
    category: "CLIP_PRODUCTION_TEAM",
    city: "Москва",
    metro: "Бауманская",
    isOnline: false,
    isAvailableNow: true,
    budgetFrom: 180000,
    bio: "Клип-продакшн команда: pre-production, съёмка, постановка, пост и цвет под музыкальные релизы.",
    services: ["Клип под ключ", "Pre-production", "Пост-продакшн и цвет"],
    credits: ["NIKA NOVA", "MIA LANE", "NEONVIBE"],
    portfolioLinks: ["https://example.com/moonlight-clip-prod"],
    contactTelegram: "https://t.me/moonlight_clip_prod",
    contactUrl: "https://example.com/moonlight-clip-prod"
  },
  {
    email: "clipteam2@artsafehub.app",
    nickname: "North Frame Production",
    safeId: "SAFE-CP-002",
    role: "SPECIALIST",
    category: "CLIP_PRODUCTION_TEAM",
    city: "Санкт-Петербург",
    metro: "Лиговский проспект",
    isOnline: true,
    isAvailableNow: false,
    budgetFrom: 140000,
    bio: "Видео-команда для музыкальных клипов и performance-видео: креатив, продакшн, графика и финальный мастер.",
    services: ["Музыкальный клип", "Сценарий и раскадровка", "Монтаж + motion графика"],
    credits: ["AURA", "North Kids", "Vera Sun"],
    portfolioLinks: ["https://example.com/north-frame-production"],
    contactTelegram: "https://t.me/north_frame_production",
    contactUrl: "https://example.com/north-frame-production"
  },
  {
    email: "designer1@artsafehub.app",
    nickname: "Signal Design",
    safeId: "SAFE-DS-001",
    role: "SPECIALIST",
    category: "DESIGNER",
    city: "Алматы",
    metro: "Жибек Жолы",
    isOnline: true,
    isAvailableNow: true,
    budgetFrom: 14000,
    bio: "Дизайнер для обложек, клиповых титров и промо-материалов: от концепта до финального пакета.",
    services: ["Дизайн обложки", "Дизайн промо-материалов", "Титры и графика для клипов"],
    credits: ["NIKA NOVA", "KZ Flow", "SONIA RED"],
    portfolioLinks: ["https://example.com/signal-design"],
    contactTelegram: "https://t.me/signal_design"
  }
];
