ALTER TYPE "FindCategory" ADD VALUE IF NOT EXISTS 'COVER_ARTIST';
ALTER TYPE "FindCategory" ADD VALUE IF NOT EXISTS 'COVER_PHOTOGRAPHER';
ALTER TYPE "FindCategory" ADD VALUE IF NOT EXISTS 'VIDEOGRAPHER';
ALTER TYPE "FindCategory" ADD VALUE IF NOT EXISTS 'DESIGNER';
